readTimeout: 10
writeTimeout: 10
idleTimeout: 15
port: 8080
debug: true
otel:
  dsn: http://echowave_secret_token@localhost:14317/2
  service: service
  version: v1.0.0
  deploymentEnv: dev
userService:
  grpcURL: localhost:8081
